## Implementing naive bayes algorithm 

In [321]:
#importing libraries
import numpy as np
import pandas as pd
from sklearn.naive_bayes import BernoulliNB
from sklearn.cross_validation import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder

In [322]:
dataframe=pd.read_csv('balance.csv')
dataframe.sample(3)

Left-weight  Left-distance  Right-weight  Right-distance Balance_scale
619            5              3             5               1             L
278            3              3             3               3             B
140            2              2             1               4             B

In [323]:
encoder=LabelEncoder()
dataframe['Balance_scale']=encoder.fit_transform(dataframe['Balance_scale'])

In [324]:
dataframe.sample(3)

Left-weight  Left-distance  Right-weight  Right-distance  Balance_scale
554            5              5             4               2              1
154            2              2             4               4              2
599            3              5             5               3              0

In [325]:
features=dataframe.columns[:-1]
target=dataframe.columns[-1]

In [326]:
train,test=train_test_split(dataframe,test_size=0.1)

In [327]:
gnb= BernoulliNB(binarize=2)

In [328]:
gnb=gnb.fit(train[features],train[target])

In [329]:
predict=gnb.predict(test[features])

In [330]:
accu=accuracy_score(test[target],predict)*100

In [331]:
accu

71.428571428571431

In [332]:
dataframe['Balance_scale']=encoder.inverse_transform(dataframe['Balance_scale'])

In [333]:
predict

array([1, 2, 1, 1, 2, 1, 1, 2, 1, 2, 1, 1, 1, 2, 2, 1, 2, 1, 2, 2, 2, 1, 2,
       1, 1, 2, 1, 1, 1, 2, 1, 1, 2, 2, 2, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1, 2,
       1, 2, 2, 1, 1, 1, 1, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2], dtype=int64)

In [334]:
np.array(test[target])

array([1, 2, 0, 1, 0, 1, 1, 2, 0, 1, 2, 1, 1, 2, 2, 1, 2, 1, 2, 2, 2, 1, 1,
       2, 1, 2, 1, 1, 2, 2, 1, 1, 2, 2, 2, 2, 1, 2, 1, 1, 0, 2, 2, 1, 0, 2,
       1, 2, 2, 2, 1, 1, 0, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2], dtype=int64)

## Implementing navie bayes with gaussian distribution

In [335]:
gnb=GaussianNB()

In [336]:
gnb=gnb.fit(train[features],train[target])

In [337]:
train.sample()

Left-weight  Left-distance  Right-weight  Right-distance  Balance_scale
292            3              4             1               4              1

In [338]:
gaupredict=gnb.predict(test[features])

In [339]:
gauaccu=accuracy_score(test[target],gaupredict)*100

In [340]:
gauaccu

87.301587301587304

In [341]:
gaupredict

array([1, 2, 1, 1, 2, 1, 1, 2, 1, 1, 2, 1, 1, 2, 2, 1, 2, 1, 2, 2, 2, 1, 1,
       2, 1, 2, 1, 1, 2, 2, 1, 1, 2, 2, 2, 2, 1, 2, 1, 1, 1, 2, 2, 1, 1, 1,
       1, 2, 2, 2, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [342]:
np.array(test[target])

array([1, 2, 0, 1, 0, 1, 1, 2, 0, 1, 2, 1, 1, 2, 2, 1, 2, 1, 2, 2, 2, 1, 1,
       2, 1, 2, 1, 1, 2, 2, 1, 1, 2, 2, 2, 2, 1, 2, 1, 1, 0, 2, 2, 1, 0, 2,
       1, 2, 2, 2, 1, 1, 0, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2], dtype=int64)